[package]
authors           = ["Procivis"]
edition.workspace = true
license           = "Apache-2.0"
name              = "one-core-uniffi"
publish           = false
version           = "0.1.0"

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
# Treat build warnings as error
strict = []

[dependencies]
async-trait              = { version = "0.1" }
futures.workspace        = true
one-core                 = { version = "0.1.0", path = "../../lib/one-core", features = ["config_json"] }
one-crypto               = { version = "0.1.0", path = "../../lib/one-crypto" }
one-dto-mapper.workspace = true
reqwest                  = { version = "0.12", default-features = false, features = ["native-tls-vendored", "json"] }
serde.workspace          = true
serde_json.workspace     = true
shared-types             = { version = "0.1.0", path = "../../lib/shared-types" }
sql-data-provider        = { version = "0.1.0", path = "../../lib/sql-data-provider" }
strum.workspace          = true
thiserror.workspace      = true
time.workspace           = true
tokio                    = { workspace = true, features = ['rt-multi-thread'] }
uniffi                   = { workspace = true, features = ["tokio"] }
url.workspace            = true
uuid.workspace           = true
zeroize.workspace        = true

[target.'cfg(target_os = "android")'.dependencies]
tracing-android    = { version = "0.2" }
tracing-subscriber = { version = "0.3" }

[lints]
workspace = true
