[package]
name                   = "one-core-uniffi"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
publish                = false

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
# Treat build warnings as error
strict = []

[dependencies]
one-core.workspace          = true
sql-data-provider.workspace = true
shared-types.workspace      = true

dto_mapper.workspace = true
uniffi.workspace     = true
serde_json.workspace = true
time.workspace       = true
tokio.workspace      = true
uuid.workspace       = true
url.workspace        = true
thiserror.workspace  = true

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }

[lints]
workspace = true
