[package]
authors           = ["Procivis"]
edition.workspace = true
license           = "Apache-2.0"
name              = "one-core-uniffi"
publish           = false
version           = "0.1.0"

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
# Treat build warnings as error
strict = []

[dependencies]
async-trait.workspace    = true
futures.workspace        = true
indexmap.workspace       = true
one-core                 = { version = "0.1.0", path = "../../lib/one-core", features = ["config_json"] }
one-crypto               = { version = "0.1.0", path = "../../lib/one-crypto" }
one-dto-mapper.workspace = true
reqwest                  = { version = "0.12", default-features = false, features = ["native-tls-vendored", "json"] }
secrecy.workspace        = true
serde.workspace          = true
serde_json.workspace     = true
shared-types             = { version = "0.1.0", path = "../../lib/shared-types" }
sql-data-provider        = { version = "0.1.0", path = "../../lib/sql-data-provider" }
strum.workspace          = true
thiserror.workspace      = true
time.workspace           = true
tokio                    = { workspace = true, features = ['rt-multi-thread'] }
tracing                  = { workspace = true }
tracing-subscriber       = { workspace = true }
uniffi                   = { workspace = true, features = ["tokio"] }
url.workspace            = true
uuid.workspace           = true

[target.'cfg(target_os = "android")'.dependencies]
tracing-android = { version = "0.2" }

[target.'cfg(target_os = "ios")'.dependencies]
tracing-oslog = { version = "0.2.0" }

[lints]
workspace = true
