[package]
name    = "one-core-uniffi"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
# Treat build warnings as error
strict = []

[dependencies]
one-core             = { version = "0.1.0", path = "../../lib/one-core" }
sql-data-provider    = { version = "0.1.0", path = "../../lib/sql-data-provider" }
dto_mapper.workspace = true
uniffi.workspace     = true
serde.workspace      = true
serde_json.workspace = true
time.workspace       = true
tokio                = { workspace = true, features = ['rt-multi-thread'] }
uuid.workspace       = true
url.workspace        = true
thiserror.workspace  = true
async-trait          = { version = "0.1" }
shared-types         = { version = "0.1.0", path = "../../lib/shared-types" }
one-providers        = { workspace = true }
one-crypto           = { workspace = true }
reqwest              = { version = "0.12", default-features = false, features = ["rustls-tls", "rustls-tls-native-roots", "json"] }

[target.'cfg(target_os = "android")'.dependencies]
tracing-android    = "0.2"
tracing-subscriber = { version = "0.3" }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }

[lints]
workspace = true
