[package]
name = "one-core-uniffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
# Treat build warnings as error
strict = []

[dependencies]
one-core = { path = "../../lib/one-core" }
sql-data-provider = { path = "../../lib/sql-data-provider" }
serde.workspace = true
serde_json.workspace = true
uniffi.workspace = true
time.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[build-dependencies]
uniffi = { version = "0.24.0", features = ["build"] }
