[package]
name                   = "one-core-uniffi"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
publish                = false

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
# Treat build warnings as error
strict = []

[dependencies]
one-core             = { version = "0.1.0", path = "../../lib/one-core" }
sql-data-provider    = { version = "0.1.0", path = "../../lib/sql-data-provider" }
dto_mapper.workspace = true
uniffi.workspace     = true
serde_json.workspace = true
time.workspace       = true
tokio.workspace      = true
uuid.workspace       = true
url.workspace        = true
thiserror.workspace  = true
shared-types         = { version = "0.1.0", path = "../../lib/shared-types" }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }

[lints]
workspace = true
