image: rust:alpine

stages:
  - build
  - test
  - publish
  - deploy

build:
  stage: build
  script:
    - apk add musl-dev
    - cargo build --release --features strict
  artifacts:
    paths:
      - target/release/mock-server

tests:
  stage: test
  dependencies: [ build ]
  script:
    - apk add musl-dev
    - cargo test --features strict

linter:clippy:
  stage: test
  dependencies: [ build ]
  script:
    - apk add musl-dev
    - rustup component add clippy
    - cargo clippy --all-targets -- -D warnings

linter:rustfmt:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
