format:
  JWT:
    type: "JWT"
    display: "format.jwt"
    order: 0 # optional to force ordering
    params:
      public:
        leeway: 60
  SDJWT:
    type: "SDJWT"
    display: "format.sdjwt"
    order: 1 # optional to force ordering
    params:
      public:
        leeway: 60
exchange:
  PROCIVIS_TEMPORARY:
    display: "exchange.procivis"
    type: "PROCIVIS_TEMPORARY"
    order: 0 # optional to force ordering
    params: null
transport:
  HTTP:
    type: "HTTP"
    display: "transport.http"
    order: 0 # optional to force ordering
    params: null
revocation:
  NONE:
    display: "revocation.none"
    order: 1
    type: "NONE"
    params: null
  STATUSLIST2021:
    display: "revocation.statuslist"
    order: 10
    type: "STATUSLIST2021"
    params: null
did:
  KEY:
    display: "did.key"
    order: 1
    type: "KEY"
    params: null
datatype:
  STRING:
    display: "datatype.string"
    type: "STRING"
    order: 100
    params: null
  NUMBER:
    display: "datatype.number"
    type: "NUMBER"
    order: 200
    params: null
  DATE:
    display: "datatype.date"
    type: "DATE"
    order: 300
    params: null
  EMAIL:
    display: "datatype.email"
    type: "STRING"
    order: 110
    params:
      public:
        autocomplete: true # optional
        placeholder: "abc@abc.com" # optional
        error: # optional
          de: "Please provide email like abc@abc.com"
          en: "Please provide email like abc@abc.com"
        pattern: '^[\w\-\.]+@([\w\-]+\.)+[\w\-]{2,4}$' # optional
  COUNT:
    display: "datatype.count"
    type: "NUMBER"
    order: 210
    params:
      public:
        min: 0 # optional
        max: 9999 # optional
        error: "datatype.count_error"
  BIRTH_DATE:
    display: "datatype.birth_date"
    type: "DATE"
    order: 310
    params:
      public:
        min: 1900-01-01 # optional
        max: "NOW" # optional
        error: "datatype.birth_date_error"
  # COUNTRY:
  #   display: "datatype.country"
  #   type: "ENUM" # not supported yet
  #   order: 2
  #   params:
  #     public:
  #       values: # optional
  #         - key: "CH" # mandatory
  #           value: "CH" # optional, defaults to key
  #           display: # optional
  #             en: "Switzerland"
  #             de: "Schweiz"
keyAlgorithm:
  EDDSA:
    display: "keyAlgorithm.eddsa"
    order: 1
    type: "EDDSA"
    params:
      public:
        algorithm: "Ed25519"
keyStorage:
  INTERNAL:
    display: "storage.internal"
    type: "INTERNAL"
    order: 2
    params:
      private:
        encryption: "my encryption key"
