format:
  JWT:
    type: "JWT"
    display: "format.jwt"
    order: 0 # optional to force ordering
    params: null # optional, per-type additional config
exchange:
  PROCIVIS_TEMPORARY:
    display: "exchange.procivis"
    type: "PROCIVIS_TEMPORARY"
    order: 0 # optional to force ordering
    params: null
did:
  KEY:
    display: "did.key"
    order: 1
    type: "KEY"
    params: null
datatype:
  EMAIL:
    display: "datatype.email"
    type: "STRING"
    order: 1
    params:
      public:
        autocomplete: true # optional
        placeholder: "abc@abc.com" # optional
        error: # optional
          de: "Please provide email like abc@abc.com"
          en: "Please provide email like abc@abc.com"
        pattern: "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$" # optional
  COUNT:
    display: "datatype.count"
    type: "NUMBER"
    order: 5
    params:
      public:
        min: 0 # optional
        max: 9999 # optional
  BIRTH_DATE:
    display: "datatype.birth_date"
    type: "DATE"
    order: 9
    params:
      public:
        min: 1900-01-01 # optional
        max: "NOW" # optional
  COUNTRY:
    display: "datatype.country"
    type: "ENUM" # not supported yet
    order: 2
    params:
      public:
        values: # optional
          - key: "CH" # mandatory
            value: "CH" # optional, defaults to key
            display: # optional
              en: "Switzerland"
              de: "Schweiz"
