# Cargo deny options
[graph]
targets = [
    # Linux
    { triple = "x86_64-unknown-linux-gnu" },
    # Windows
    { triple = "x86_64-pc-windows-gnu" },
    # Mobile (Android)
    { triple = "i686-linux-android" },
    { triple = "armv7-linux-androideabi" },
    { triple = "aarch64-linux-android" },
    # Mobile (iOS)
    { triple = "aarch64-apple-ios" },
]

all-features        = false
no-default-features = false

# This section is considered when running `cargo deny check advisories`
# More documentation for the advisories section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
version = 2
yanked  = "deny"

ignore = [
    { id = "RUSTSEC-2023-0071", reason = "no safe upgrade available, can be avoided by not using RSA in mysql server" },
    { id = "RUSTSEC-2024-0370", reason = "proc-macro-error crate unmaintained, indirect dependency of a few libs" },
    { id = "RUSTSEC-2022-0040", reason = "`owning_ref` doesn't seem to be used anywhere inside json-ld" },
    { id = "RUSTSEC-2024-0388", reason = "unmaintained dependency of json-ld 0.15. Should be resolved in ONE-3321" },
]

# This section is considered when running `cargo deny check licenses`
# More documentation for the licenses section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "CECILL-B",
    "ISC",
    "MIT",
    "MIT-0",
    "Unicode-DFS-2016",
    "Unicode-3.0",
    "Zlib",
    "BSL-1.0",
]
confidence-threshold = 0.8
version = 2

exceptions = [
    # Allow MPL-2.0 for libraries we do not modify
    { allow = ["MPL-2.0"], name = "webpki-roots", version = "*" },
    { allow = ["MPL-2.0"], name = "resiter", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_bindgen", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_core", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_internal_macros", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_macros", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_meta", version = "*" },
    { allow = ["MPL-2.0"], name = "uniffi_udl", version = "*" },
    { allow = ["MPL-2.0"], name = "bitmaps", version = "*" },
    { allow = ["MPL-2.0"], name = "im", version = "*" },
    { allow = ["MPL-2.0"], name = "sized-chunks", version = "*" },

    # Allow OpenSSL for ring
    { allow = ["OpenSSL"], name = "ring", version = "*" },
]

[licenses.private]
ignore = true

# Clarify ring crate license (LICENSE file not properly detected)
[[licenses.clarify]]
expression    = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
name          = "ring"

# This section is considered when running `cargo deny check bans`.
# More documentation about the 'bans' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
allow                      = []
deny                       = []
external-default-features  = "allow"
multiple-versions          = "allow"
wildcards                  = "deny"
workspace-default-features = "allow"

# This section is considered when running `cargo deny check sources`.
# More documentation about the 'sources' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
allow-git = [
    "https://github.com/procivis/pairing_crypto",
    "https://github.com/procivis/dilithium",
    "https://github.com/procivis/json-ld",
    "https://github.com/procivis/blstrs",
]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
unknown-git = "deny"
unknown-registry = "deny"
