[package]
authors           = ["Procivis"]
edition.workspace = true
license           = "Apache-2.0"
name              = "uniffi-bindgen"
publish           = false
version           = "0.1.0"

[dependencies]
uniffi = { workspace = true, features = ["cli"] }

[lints]
workspace = true
