[package]
name                   = "uniffi-bindgen"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
publish                = false

[dependencies]
uniffi.workspace = true

[lints]
workspace = true
