pub mod claim;
pub mod claim_schema;
pub mod credential;
pub mod credential_schema;
pub mod credential_schema_claim_schema;
pub mod credential_state;
pub mod did;
pub mod key;
pub mod organisation;
pub mod proof;
pub mod proof_claim;
pub mod proof_schema;
pub mod proof_schema_claim_schema;
pub mod proof_state;

pub use claim::Entity as Claim;
pub use claim_schema::Entity as ClaimSchema;
pub use credential::Entity as Credential;
pub use credential_schema::Entity as CredentialSchema;
pub use credential_schema_claim_schema::Entity as CredentialSchemaClaimSchema;
pub use credential_state::Entity as CredentialState;
pub use did::Entity as Did;
pub use key::Entity as Key;
pub use organisation::Entity as Organisation;
pub use proof::Entity as Proof;
pub use proof_claim::Entity as ProofClaim;
pub use proof_schema::Entity as ProofSchema;
pub use proof_schema_claim_schema::Entity as ProofSchemaClaimSchema;
pub use proof_state::Entity as ProofState;
