keyStorage:
  SECURE_ELEMENT:
    display: "keyStorage.secureElement"
    type: "SECURE_ELEMENT"
    order: 3
    params:
      private:
        aliasPrefix: "ch.procivis.one.wallet.keys"
cacheEntites:
  JSON_LD_CONTEXT:
    cacheSize: 100
transport:
  BLE:
    type: "BLE"
    display: "transport.ble"
    disabled: false
    order: 1
