app:
  allowInsecureHttpTransport: false
  traceLevel: "info,sea_orm=warn,sqlx::query=error"
cacheEntities:
  STATUS_LIST_CREDENTIAL:
    cacheSize: 100
  DID_DOCUMENT:
    cacheSize: 100
  JSON_LD_CONTEXT:
    cacheSize: 100
  VCT_METADATA:
    cacheSize: 100
  JSON_SCHEMA:
    cacheSize: 100
  TRUST_LIST:
    cacheSize: 100
transport:
  BLE:
    type: "BLE"
    display: "transport.ble"
    enabled: true
    order: 1
  MQTT:
    type: "MQTT"
    display: "transport.mqtt"
    enabled: true
    order: 2
    params:
      private:
        brokerUrl: "mqtts://mqtt.dev.procivis-one.com:8883"
verificationProtocol:
  OPENID4VP_PROXIMITY_DRAFT00:
    display: "exchange.openid00_proximity"
    order: 4
    type: "OPENID4VP_PROXIMITY_DRAFT00"
    params: {}
  SCAN_TO_VERIFY:
    type: "SCAN_TO_VERIFY"
    enabled: false
    display: "exchange.scanToVerify"
    order: 5
  ISO_MDL:
    type: "ISO_MDL"
    display: "exchange.isoMdl"
    order: 6
  OPENID4VP_DRAFT25_EUDI:
    display:
      en: "OpenID4VP draft 25 (EUDI)"
      de: "OpenID4VP draft 25 (EUDI)"
    order: 8
    type: "OPENID4VP_DRAFT25"
    params:
      public:
        useRequestUri: true
        urlScheme: eudi-openid4vp
        x509CaCertificate: MIIC3TCCAoOgAwIBAgIUEwybFc9Jw-az3r188OiHDaxCfHEwCgYIKoZIzj0EAwMwXDEeMBwGA1UEAwwVUElEIElzc3VlciBDQSAtIFVUIDAyMS0wKwYDVQQKDCRFVURJIFdhbGxldCBSZWZlcmVuY2UgSW1wbGVtZW50YXRpb24xCzAJBgNVBAYTAlVUMB4XDTI1MDMyNDIwMjYxNFoXDTM0MDYyMDIwMjYxM1owXDEeMBwGA1UEAwwVUElEIElzc3VlciBDQSAtIFVUIDAyMS0wKwYDVQQKDCRFVURJIFdhbGxldCBSZWZlcmVuY2UgSW1wbGVtZW50YXRpb24xCzAJBgNVBAYTAlVUMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEesDKj9rCIcrGj0wbSXYvCV953bOPSYLZH5TNmhTz2xa7VdlvQgQeGZRg1PrF5AFwt070wvL9qr1DUDdvLp6a1qOCASEwggEdMBIGA1UdEwEB_wQIMAYBAf8CAQAwHwYDVR0jBBgwFoAUYseURyi9D6IWIKeawkmURPEB08cwEwYDVR0lBAwwCgYIK4ECAgAAAQcwQwYDVR0fBDwwOjA4oDagNIYyaHR0cHM6Ly9wcmVwcm9kLnBraS5ldWRpdy5kZXYvY3JsL3BpZF9DQV9VVF8wMi5jcmwwHQYDVR0OBBYEFGLHlEcovQ-iFiCnmsJJlETxAdPHMA4GA1UdDwEB_wQEAwIBBjBdBgNVHRIEVjBUhlJodHRwczovL2dpdGh1Yi5jb20vZXUtZGlnaXRhbC1pZGVudGl0eS13YWxsZXQvYXJjaGl0ZWN0dXJlLWFuZC1yZWZlcmVuY2UtZnJhbWV3b3JrMAoGCCqGSM49BAMDA0gAMEUCIQCe4R9rO4JhFp821kO8Gkb8rXm4qGG_e5_Oi2XmnTQqOQIgfFs-LDbnP2_j1MB4rwZ1FgGdpr4oyrFB9daZyRIcP90
        verifier:
          supportedClientIdSchemes: [x509_san_dns, redirect_uri, verifier_attestation, did]
        holder:
          supportedClientIdSchemes: [redirect_uri, verifier_attestation, did, x509_san_dns]
        redirectUri:
          enabled: true
          allowedSchemes: ["https"]
keyStorage:
  SECURE_ELEMENT:
    display: "keyStorage.secureElement"
    type: "SECURE_ELEMENT"
    order: 3
    params:
      private:
        aliasPrefix: "ch.procivis.one.wallet.keys"
  UBIQU_RSE:
    display: "keyStorage.ubiqu"
    type: "REMOTE_SECURE_ELEMENT"
    enabled: false
    order: 10
datatype:
  FULL-DATE:
    display: "datatype.string"
    type: "STRING"
    order: 101
    params: null
  UINT:
    display: "datatype.string"
    type: "STRING"
    order: 102
    params: null
  BOOL:
    display: "datatype.string"
    type: "STRING"
    order: 103
    params: null
trustManagement:
  SIMPLE_TRUST_LIST:
    params:
      public:
        enablePublishing: false
