app:
  allowInsecureHttpTransport: false
transport:
  HTTP:
    disabled: true
  BLE:
    type: "BLE"
    display: "transport.ble"
    disabled: false
    order: 1
    params:
      private:
        verifierName: "OneVerifier"
  MQTT:
    type: "MQTT"
    display: "transport.mqtt"
    disabled: false
    order: 2
    params:
      private:
        brokerUrl: "https://desk.dev.procivis-one.com/"
keyStorage:
  SECURE_ELEMENT:
    display: "keyStorage.secureElement"
    type: "SECURE_ELEMENT"
    order: 3
    params:
      private:
        aliasPrefix: "ch.procivis.one.wallet.keys"
exchange:
  SCAN_TO_VERIFY:
    type: "SCAN_TO_VERIFY"
    display: "exchange.scanToVerify"
    order: 2
  ISO_MDL:
    type: "ISO_MDL"
    display: "exchange.isoMdl"
    order: 3
