app:
  allowInsecureHttpTransport: false
cacheEntities:
  STATUS_LIST_CREDENTIAL:
    cacheSize: 100
  DID_DOCUMENT:
    cacheSize: 100
  JSON_LD_CONTEXT:
    cacheSize: 100
keyStorage:
  SECURE_ELEMENT:
    display: "keyStorage.secureElement"
    type: "SECURE_ELEMENT"
    order: 3
    params:
      private:
        aliasPrefix: "ch.procivis.one.wallet.keys"
transport:
  BLE:
    type: "BLE"
    display: "transport.ble"
    disabled: false
    order: 1
exchange:
  ISO_MDL:
    type: "ISO_MDL"
    display: "exchange.isoMdl"
    order: 3
