app:
  allowInsecureHttpTransport: false
  traceLevel: "info,sea_orm=warn,sqlx::query=error"
cacheEntities:
  STATUS_LIST_CREDENTIAL:
    cacheSize: 100
  DID_DOCUMENT:
    cacheSize: 100
  JSON_LD_CONTEXT:
    cacheSize: 100
  VCT_METADATA:
    cacheSize: 100
  JSON_SCHEMA:
    cacheSize: 100
  TRUST_LIST:
    cacheSize: 100
transport:
  BLE:
    type: "BLE"
    display: "transport.ble"
    disabled: false
    order: 1
  MQTT:
    type: "MQTT"
    display: "transport.mqtt"
    disabled: false
    order: 2
    params:
      private:
        brokerUrl: "mqtts://mqtt.dev.procivis-one.com:8883"
exchange:
  SCAN_TO_VERIFY:
    type: "SCAN_TO_VERIFY"
    disabled: true
    display: "exchange.scanToVerify"
    order: 2
  ISO_MDL:
    type: "ISO_MDL"
    display: "exchange.isoMdl"
    order: 3
keyStorage:
  SECURE_ELEMENT:
    display: "keyStorage.secureElement"
    type: "SECURE_ELEMENT"
    order: 3
    params:
      private:
        aliasPrefix: "ch.procivis.one.wallet.keys"
  UBIQU_RSE:
    display: "keyStorage.ubiqu"
    type: "REMOTE_SECURE_ELEMENT"
    disabled: true
    order: 10
datatype:
  FULL-DATE:
    display: "datatype.string"
    type: "STRING"
    order: 101
    params: null
  UINT:
    display: "datatype.string"
    type: "STRING"
    order: 102
    params: null
  BOOL:
    display: "datatype.string"
    type: "STRING"
    order: 103
    params: null
trustManagement:
  SIMPLE_TRUST_LIST:
    params:
      public:
        enablePublishing: false
