app:
  allowInsecureHttpTransport: false
  traceLevel: "info,sea_orm=warn,sqlx::query=error"
cacheEntities:
  STATUS_LIST_CREDENTIAL:
    cacheSize: 100
  DID_DOCUMENT:
    cacheSize: 100
  JSON_LD_CONTEXT:
    cacheSize: 100
  VCT_METADATA:
    cacheSize: 100
  JSON_SCHEMA:
    cacheSize: 100
  TRUST_LIST:
    cacheSize: 100
transport:
  BLE:
    type: "BLE"
    display: "transport.ble"
    enabled: true
    order: 1
  MQTT:
    type: "MQTT"
    display: "transport.mqtt"
    enabled: true
    order: 2
    params:
      private:
        brokerUrl: "mqtts://mqtt.dev.procivis-one.com:8883"
verificationProtocol:
  OPENID4VP_PROXIMITY_DRAFT00:
    display: "exchange.openid00_proximity"
    order: 5
    type: "OPENID4VP_PROXIMITY_DRAFT00"
    params: {}
  SCAN_TO_VERIFY:
    type: "SCAN_TO_VERIFY"
    enabled: false
    display: "exchange.scanToVerify"
    order: 6
  ISO_MDL:
    type: "ISO_MDL"
    display: "exchange.isoMdl"
    order: 7
keyStorage:
  SECURE_ELEMENT:
    display: "keyStorage.secureElement"
    type: "SECURE_ELEMENT"
    order: 3
    params:
      private:
        aliasPrefix: "ch.procivis.one.wallet.keys"
  UBIQU_RSE:
    display: "keyStorage.ubiqu"
    type: "REMOTE_SECURE_ELEMENT"
    enabled: false
    order: 10
trustManagement:
  SIMPLE_TRUST_LIST:
    params:
      public:
        enablePublishing: false
