app:
  allowInsecureHttpTransport: false
transport:
  BLE:
    type: "BLE"
    display: "transport.ble"
    disabled: false
    order: 1
    params:
      private:
        verifierName: "OneVerifier"
  HTTP:
    disabled: true
keyStorage:
  SECURE_ELEMENT:
    display: "keyStorage.secureElement"
    type: "SECURE_ELEMENT"
    order: 3
    params:
      private:
        aliasPrefix: "ch.procivis.one.wallet.keys"
exchange:
  SCAN_TO_VERIFY:
    type: "SCAN_TO_VERIFY"
    display: "exchange.scanToVerify"
    order: 2
  ISO_MDL:
    type: "ISO_MDL"
    display: "exchange.isoMdl"
    order: 3
