app:
  allowInsecureHttpTransport: false
  traceLevel: "info,sea_orm=warn,sqlx::query=error"
cacheEntities:
  STATUS_LIST_CREDENTIAL:
    cacheSize: 100
  DID_DOCUMENT:
    cacheSize: 100
  JSON_LD_CONTEXT:
    cacheSize: 100
  VCT_METADATA:
    cacheSize: 100
  JSON_SCHEMA:
    cacheSize: 100
  TRUST_LIST:
    cacheSize: 100
transport:
  BLE:
    type: "BLE"
    display: "transport.ble"
    enabled: true
    order: 1
  MQTT:
    type: "MQTT"
    display: "transport.mqtt"
    enabled: true
    order: 2
    params:
      private:
        brokerUrl: "mqtts://mqtt.dev.procivis-one.com:8883"
issuanceProtocol:
  OPENID4VCI_DRAFT13_SWIYU:
    display:
      en: "OpenID4VCI (SWIYU)"
      de: "OpenID4VCI (SWIYU)"
    order: 2
    type: "OPENID4VCI_DRAFT13_SWIYU"
    params:
      public:
        urlScheme: swiyu
        credentialOfferByValue: true
        preAuthorizedCodeExpiresIn: 300
        tokenExpiresIn: 86400
        refreshExpiresIn: 7776000 # 90 days in seconds
        redirectUri:
          enabled: true
          allowedSchemes: ["https"]
verificationProtocol:
  OPENID4VP_PROXIMITY_DRAFT00:
    display: "exchange.openid00_proximity"
    order: 4
    type: "OPENID4VP_PROXIMITY_DRAFT00"
    params: {}
  SCAN_TO_VERIFY:
    type: "SCAN_TO_VERIFY"
    enabled: false
    display: "exchange.scanToVerify"
    order: 5
  ISO_MDL:
    type: "ISO_MDL"
    display: "exchange.isoMdl"
    order: 6
  OPENID4VP_DRAFT20_SWIYU:
    display:
      en: "OpenID4VP draft 20 (SWIYU)"
      de: "OpenID4VP draft 20 (SWIYU)"
    order: 7
    type: "OPENID4VP_DRAFT20_SWIYU"
    params:
      public:
        urlScheme: https
        useRequestUri: true
        verifier:
          supportedClientIdSchemes: [redirect_uri, verifier_attestation, did]
          defaultClientIdScheme: verifier_attestation
        holder:
          supportedClientIdSchemes: [redirect_uri, verifier_attestation, did]
        redirectUri:
          enabled: true
          allowedSchemes: ["https"]
        predefinedClientMetadata:
          vp_formats:
            dc+sd-jwt:
              sd-jwt_alg_values: ["ES256"]
              kb-jwt_alg_values: ["ES256"]
format:
  SD_JWT_VC_SWIYU:
    type: "SD_JWT_VC"
    display:
      en: "IETF SD-JWT VC (SWIYU)"
      de: "IETF SD-JWT VC (SWIYU)"
    order: 201
    params:
      public:
        leeway: 60
        embedLayoutProperties: true
        swiyuMode: true
keyStorage:
  SECURE_ELEMENT:
    display: "keyStorage.secureElement"
    type: "SECURE_ELEMENT"
    order: 3
    params:
      private:
        aliasPrefix: "ch.procivis.one.wallet.keys"
  UBIQU_RSE:
    display: "keyStorage.ubiqu"
    type: "REMOTE_SECURE_ELEMENT"
    enabled: false
    order: 10
datatype:
  FULL-DATE:
    display: "datatype.string"
    type: "STRING"
    order: 101
    params: null
  UINT:
    display: "datatype.string"
    type: "STRING"
    order: 102
    params: null
  BOOL:
    display: "datatype.string"
    type: "STRING"
    order: 103
    params: null
  SWIYU_PICTURE:
    display:
      en: "Picture (SWIYU)"
      de: "Bild (SWIYU)"
    type: "FILE"
    order: 403
    params:
      public:
        accept:
          - image/jpeg
        fileSize: 4194304
        showAs: IMAGE
trustManagement:
  SIMPLE_TRUST_LIST:
    params:
      public:
        enablePublishing: false
