cacheEntites:
  JSON_LD_CONTEXT:
    cacheSize: 100
transport:
  BLE:
    type: "BLE"
    display: "transport.ble"
    disabled: false
    order: 1
    params:
      private:
        verifierName: "OneVerifier"
  HTTP:
    disabled: true
exchange:
  SCAN_TO_VERIFY:
    type: "SCAN_TO_VERIFY"
    display: "exchange.scanToVerify"
    order: 2
