# Default values for onecorechart.

sentry:
  env: ""

replicaCount: 1

image:
  repository: registry.gitlab.procivis.ch/procivis/one/one-core/procivis
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: gitlab-credentials-dev-cluster

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  fluentd.active: "true"

podSecurityContext: {}

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations:
    traefik.ingress.kubernetes.io/router.tls.certresolver: le
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts: []
  tls: []


resources:
  requests:
    cpu: 50m
    memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

baseUrl: ""

configs:
  - "config.yml"


config:
  azureKeyVault:
    adTenantId: ""
    clientId: ""
    clientSecret: ""
    vaultUrl: ""


mariadb:
  enabled: true
  architecture: standalone
  auth:
    database: "one-core"
    username: "core_user"
    rootPassword: ""
    password: ""
  metrics:
    enabled: true
  primary:
    persistence:
      size: 8Gi
    configuration: |-
      [mysqld]
      skip-name-resolve
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mariadb
      datadir=/bitnami/mariadb/data
      plugin_dir=/opt/bitnami/mariadb/plugin
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      tmpdir=/opt/bitnami/mariadb/tmp
      max_allowed_packet=16M
      bind-address=*
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
      log-error=/opt/bitnami/mariadb/logs/mysqld.log
      character-set-server=utf8mb4
      collation-server=utf8mb4_general_ci
      slow_query_log=0
      long_query_time=10.0

      [client]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mariadb/plugin

      [manager]
      port=3306
      socket=/opt/bitnami/mariadb/tmp/mysql.sock
      pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
