mod create_credential_tests;
mod delete_credential_tests;
mod get_credential_tests;
mod list_credential_tests;
mod reactivate_credential_tests;
mod revoke_check_tests;
mod revoke_credential_tests;
mod share_credential_tests;
mod suspend_credential_tests;
