stages:
  - docs

build:docs:
  stage: docs
  needs: []
  script:
    - cargo doc --no-deps --release
  after_script:
    - mkdir -p target/doc
    - mv ${CARGO_TARGET_DIR}/doc target/doc
  artifacts:
    expire_in: 2 day
    paths:
      - target/doc
  extends:
    - .rule:deploy:test

publish:docs:
  stage: docs
  needs:
    - job: build:docs
      artifacts: true
  variables:
    DOCKERFILE_PATH: docs/docker/Dockerfile
    APP_FLAVOR: docs
  extends:
    - .docker_publish
    - .rule:deploy:test

deploy:docs:
  stage: docs
  needs:
    - job: publish:docs
  extends:
    - .deploy_trigger
    - .rule:deploy:test
  variables:
    HELM_APP_NAME: one-core-docs
    HELM_PATH: charts/one-core-docs-chart
    HELM_VALUES_FILE: values/docs.procivis-one.yaml
    K8S_NAMESPACE: trial
    RESOURCE_GROUP: $DEMO_RESOURCE_GROUP
    CLUSTER_NAME: $DEMO_CLUSTER_NAME
    DEPLOY_IMAGE_TAG: $APP_VERSION
