[package]
name = "core-server"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
# Treat build warnings as error
strict = []

[dependencies]
one-core = { path = "../../lib/one-core", features = ["mysql"] }

axum.workspace = true
serde.workspace = true
serde_json.workspace = true
shadow-rs.workspace = true
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa.workspace = true
uuid.workspace = true
validator.workspace = true

tower-http = { version = "0.4", features = ["trace"] }
tokio = { version = "1.26", features = ["full"] }
utoipa-swagger-ui = { version = "3.0", features = ["axum"] }
envmnt = "0.10.4"
panic-handler = "2.1.2"
serde_variant = "0.1.2"

[build-dependencies]
shadow-rs.workspace = true
envmnt = "0.10.4"
