[package]
name = "core-server"
version = "0.1.0"
edition = "2021"
build = "build.rs"
publish = false

[features]
# Treat build warnings as error
strict = []

[dependencies]
one-core = { version = "0.1.0", path = "../../lib/one-core" }
sql-data-provider = { version = "0.1.0", path = "../../lib/sql-data-provider", features = [
    "mysql",
] }

axum.workspace = true
ct-codecs.workspace = true
dto_derive.workspace = true
serde.workspace = true
serde_json.workspace = true
shadow-rs.workspace = true
thiserror.workspace = true
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
validator.workspace = true
figment.workspace = true

tower-http = { version = "0.4", features = ["trace"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
utoipa = { version = "4.0.0", features = ["uuid", "axum_extras"] }
utoipa-swagger-ui = { version = "4.0.0", features = ["axum"] }
serde_qs = "0.12.0"
sentry = { version = "0.31.7", default-features = false, features = [
    "backtrace",
    "panic",
    "rustls",
    "reqwest",
] }
sentry-tracing = "0.31.7"
dto_mapper = { workspace = true }
url = { workspace = true }

[build-dependencies]
shadow-rs.workspace = true
