[package]
name = "core-server"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
# Treat build warnings as error
strict = []

[dependencies]
one-core.workspace = true
migration.workspace = true

sea-orm.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa.workspace = true

shadow-rs.workspace = true

axum = { version = "0.6", features = ["macros"] }
tower-http = { version = "0.4", features = [ "trace"] }
tokio = { version = "1.26", features = ["full"]}
utoipa-swagger-ui = {version = "3.0", features = ["axum"]}
envmnt = "0.10.4"
panic-handler = "2.1.2"
uuid = { version = "1", features = ["v4"] }
validator = { version = "0.16.0", features = ["derive"] }

[build-dependencies]
shadow-rs.workspace = true
envmnt = "0.10.4"
