[package]
name = "core-server"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
# Treat build warnings as error
strict = []

[dependencies]
one-core = { version = "0.1.0", path = "../../lib/one-core" }
sql-data-provider = { version = "0.1.0", path = "../../lib/sql-data-provider", features = ["mysql"] }

axum.workspace = true
dto_derive.workspace = true
serde.workspace = true
serde_json.workspace = true
shadow-rs.workspace = true
time.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
utoipa.workspace = true
uuid.workspace = true
validator.workspace = true
figment.workspace = true

tower-http = { version = "0.4", features = ["trace"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
utoipa-swagger-ui = { version = "3.0", features = ["axum"] }
panic-handler = "2.1.2"
serde_variant = "0.1.2"
envy = "0.4.2"
serde_qs = "0.12.0"
sentry = { version = "0.31.7", default-features = false, features = [
    "backtrace",
    "panic",
    "rustls",
    "reqwest",
] }
sentry-tracing = "0.31.7"

[build-dependencies]
shadow-rs.workspace = true
